export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transactions with zero fees",
  description:
    "Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.",
  imgStart: false,
  img: require("../../images/svg-1.svg"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
  buttonLabel: "Get Started",
  imgStart: false,
  dark: false,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Unlimited Access",
  headline: "Unlimited Transactions with zero fees",
  description:
    "Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.",
  imgStart: false,
  img: require("../../images/svg-2.svg"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
  buttonLabel: "Learn More",
  imgStart: true,
  dark: true,
  darkText: true,
};
export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Premium Bank",
  headline: "Unlimited Transactions with zero fees",
  description:
    "Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.",
  imgStart: false,
  img: require("../../images/svg-3.svg"),
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
  buttonLabel: "Get Started",
  imgStart: false,
  dark: true,
  darkText: true,
};
